### ISSUE TITLE
GETTING NULL FILE!!!!

### ISSUE THREAD

**Issue by sami3898** [jim-at-jibba/rn-custom-image-keyboard#1]
HELLO Brother,
Your code is must useful but whenever I try to select an image the app getting crashed.
after debugging I realize that I'm getting file as Null in this line

final File file = getFileForResource(ImageKeyboard.this, getResources().getIdentifier(view.getTag().toString(), "raw", getPackageName()), imagesDir, "${view.getTag().toString()}.png");

Please connect with me and tell me how to resolve this issue.

Thank you

**Comment by rzhou1999** [comment]
Well, this example app is a little old (so is this issue), but I just went through it myself and had this exact same problem. I eventually figured it out so I figured I should share. So it turns out that this is actually because there's a missing line in ImageKeyboard.java (the full file path has some directories that aren't created I believe):

```
...
public View onCreateInputView() {
    final File imagesDir = new File(getFilesDir(), "images");
    imagesDir.mkdirs(); //ADD THIS LINE
    RelativeLayout KeyboardLayout = (RelativeLayout) getLayoutInflater().inflate(R.layout.keyboard_layout, null);
    LinearLayout ImageContainer = (LinearLayout) KeyboardLayout.findViewById(R.id.imageContainer);
...
```
